#!/usr/bin/env node
const async   = require('async');
const path    = require('path');
const args    = require('yargs').argv;

// check if the port was given
if(!args.port) {

  // flush and exit
  process.stderr.write('No --port provided for Redis server\n', function() {

    // exit
    process.exit(1);

  });

} else if(!args.host) {

  // flush and exit
  process.stderr.write('No --host provided for Redis server\n', function() {

    // exit
    process.exit(1);

  });

} else if(args._.length === 0) {

  // flush and exit
  process.stderr.write('No blacklists given to load, see https://www.phishtank.com/developer_info.php and download the JSON database\n', function() {

    // exit
    process.exit(1);

  });

} else {

  // loop with each file
  async.eachLimit(args._, 1, function(file, cb) {

    // get the path 
    var filename = path.resolve(file);

    // debugging
    console.log('processing ' + filename + ':');

    // done
    require('./index.js').boot({

      host:   args.host,
      port:   args.port,
      debug:  args.debug ? args.debug === true : true,
      file:   filename

    }, cb);

  }, function(err) {

    // decide on how to exit
    if(err) 
      process.exit(1);
    else 
      process.exit(0);

  });

}
